#!/bin/bash

#SBATCH --job-name=t5-spider-gpu-vanilla-mirror
#SBATCH --output=job.%j.out
#SBATCH --cpus-per-task=8
#SBATCH --gres=gpu
#SBATCH --time=05:00:00
#SBATCH --partition=brown, red
#SBATCH --nodelist=desktop18, desktop17, cn3, cn4, cn5, cn8

echo "Running on $(hostname):"

source /home/jato/venv/bin/activate

nvidia-smi

cd /home/jato/T5/
python T5_SP_GraphQL_Spider_vanilla_mirror.py

deactivate